apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: application
  labels:
    app.kubernetes.io/name: employees
    app.kubernetes.io/component: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app.kubernetes.io/name: employees
        app.kubernetes.io/component: frontend
    spec:
      containers:
        - name: websrv-images
          image: 844099387134.dkr.ecr.us-east-1.amazonaws.com/websrv-images:v0.1
          env:
            - name: DBPWD
              value: pw
            - name: DBUSER
              value: root
            - name: DBHOST
              value: "mysql.database.svc.cluster.local"
            - name: DBPORT
              value: "3306"
          ports:
            - containerPort: 8080